export var fakeTeacher = [
  {
    id: 1,
    name: "John Doe",
    rating: 4.7,
    location: "Dhaka, Bangladesh",
    image: "",
    price: 45,
    assignments: 10,
    memberSince: "25 July, 2020",
  },
  {
    id: 2,
    name: "Jane Doe",
    rating: 4.7,
    location: "Dhaka, Bangladesh",
    image: "",
    price: 45,
    assignments: 10,
    memberSince: "25 July, 2020",
  },
  {
    id: 3,
    name: "Jack Doe",
    rating: 4.7,
    location: "Dhaka, Bangladesh",
    image: "",
    price: 45,
    assignments: 10,
    memberSince: "25 July, 2020",
  },
  {
    id: 4,
    name: "John Doe",
    rating: 4.7,
    location: "Dhaka, Bangladesh",
    image: "",
    price: 45,
    assignments: 10,
    memberSince: "25 July, 2020",
  },
  {
    id: 5,
    name: "Jane Doe",
    rating: 4.7,
    location: "Dhaka, Bangladesh",
    image: "",
    price: 45,
    assignments: 10,
    memberSince: "25 July, 2020",
  },
  {
    id: 6,
    name: "Jack Doe",
    rating: 4.7,
    location: "Dhaka, Bangladesh",
    image: "",
    price: 45,
    assignments: 10,
    memberSince: "25 July, 2020",
  },
  {
    id: 7,
    name: "John Doe",
    rating: 4.7,
    location: "Dhaka, Bangladesh",
    image: "",
    price: 45,
    assignments: 10,
    memberSince: "25 July, 2020",
  },
  {
    id: 8,
    name: "Jane Doe",
    rating: 4.7,
    location: "Dhaka, Bangladesh",
    image: "",
    price: 45,
    assignments: 10,
    memberSince: "25 July, 2020",
  },
  {
    id: 9,
    name: "Jack Doe",
    rating: 4.7,
    location: "Dhaka, Bangladesh",
    image: "",
    price: 45,
    assignments: 10,
    memberSince: "25 July, 2020",
  },
];

// export default users;
